### ISSUE TITLE
Developing popRF model for India using popRF package

### ISSUE THREAD

**Issue by pankajkr394** [wpgp/popRF#7]
I am trying to estimate population in case of India using the popRF package in R. I followed the popRF tutorial. The tabular file (.csv) containing the IDs of the subnational areas and the corresponding total population is required as input for the model. But, it is not available in the population tables to download. (https://data.worldpop.org/GIS/Population/Global_2000_2020/CensusTables/)
How can I access the population table to make use of this package? 

Thanks and Regards
Pankaj

**Comment by jjniev01** [comment]
Morning pankajkr394,

If I remember correctly (since the project the mastergrid was developed in ended in 2018), and @bondarenkom might have access to more records than I do currently, India was one of 13 countries that we did not have access to the underlying subnational area geometry due to licensing. We had a project partner who did have access to those commercial or restricted data run the models for us and provide us the output.

But you do not need any preprovided data from us/WorldPop to be able to make your own disaggregated gridded population datasets. As it mentions in the vignette/tutorial, you can provide your own boundaries.

For example, you could go download current shapefiles from the Indian census, rasterise those boundaries where the resulting raster has values representing the area IDs of your own making, and you then extract the population data (with corresponding area IDs) to a .csv file. You then would provide your rasterised boundaries as the "mastergrid" and provide the .csv you made as the tabular population data.

Hopefully this helps further explains the solution for you.

**Comment by pankajkr394** [comment]
Thank you for your answer. I have tried to rasterise the boundaries and extract the population data in QGIS. But, the program stops everytime, probably due to big size of the shapefile.
